source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object'
gem 'faker'
gem 'data_magic'
gem 'require_all'

gem 'activerecord'
gem 'factory_girl'
gem 'database_cleaner'
gem 'sqlite3'